export enum RepositoryEnum {
  CAREER_REPOSITORY = 'CAREER_REPOSITORY',
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
  CURRICULUM_REPOSITORY = 'CURRICULUM_REPOSITORY',
  INFORMATION_STUDENT_REPOSITORY = 'INFORMATION_STUDENT_REPOSITORY',
  INFORMATION_TEACHER_REPOSITORY = 'INFORMATION_TEACHER_REPOSITORY',
  INSTITUTION_REPOSITORY = 'INSTITUTION_REPOSITORY',
  STUDENT_REPOSITORY = 'STUDENT_REPOSITORY',
  SUBJECT_REPOSITORY = 'SUBJECT_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
}
