export * from './catalogues.service';
export * from './students.service';
export * from './careers.service';
export * from './curricula.service';
export * from './information-students.service';
export * from './information-teachers.service';
export * from './institutions.service';
export * from './students.service';
export * from './subjects.service';
